package com.pluckerpluck.brawlhalla.client;

import org.junit.BeforeClass;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.pluckerpluck.brawlhalla.client.REST.BasicPlayer;
import com.pluckerpluck.brawlhalla.client.REST.LeaderboardPlayer;
import com.pluckerpluck.brawlhalla.client.types.Region;
import com.pluckerpluck.brawlhalla.client.types.Bracket;

import static org.junit.Assert.*;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.Properties;

public class APITest {

	private static API service;

	@BeforeClass
	public static void loadConfig() throws FileNotFoundException, IOException {
		Properties prop = new Properties();
		InputStream input = new FileInputStream("settings.testing");

		prop.load(input);

		String apiKey = prop.getProperty("apikey");

		service = new API(apiKey);

	}

	@Test
	public void testSearch() throws IOException {
		BasicPlayer player = service.search("76561197999015527");

		assertEquals("Name check", "Pluckerpluck", player.getName());
		assertEquals("ID check", 60248, player.getID());
	}

	@Test
	public void testRankingsPage() throws IOException {
		List<LeaderboardPlayer> players = service.getRankingsPage(Bracket.ONE_VS_ONE, Region.EU, 1);
		assertEquals("Page size", 50, players.size());
	}


}
